### ISSUE TITLE
Missing use JsonSchema\Uri\UriResolver

### ISSUE THREAD

**Issue by guillaumedelre** [Nicofuma/behatch-contexts#1]
Hello in https://github.com/Nicofuma/behatch-contexts/blob/master/src/Json/JsonInspector.php#L38 you call resolve method with 2 params. For the second one you forget the use in top of class (use JsonSchema\Uri\UriResolver).

**Comment by Nicofuma** [comment]
Fixed and 2.5.0.2 tagged

Thanks for the notice
